using System.ComponentModel;

namespace Quixotic.Common.Tokens
{
    public enum TokenType
    {
        StringLiteral,
        NumberLiteral,
        True,
        False,
        Identifier,
        Print,
        Let,
        If,
        Then,
        Else,
        EndIf,
        EndFor,
        EndConstruct,
        EndType,
        Do,
        While,
        Until,
        Loop,
        Continue,
        Break,
        EqualTo,
        NotEqualTo,
        GreaterThan,
        GreaterThanOrEqualTo,
        LessThan,
        LessThanOrEqualTo,
        Assignment,

        [Description("Open Parenthesis")]
        OpenParen,

        [Description("Close Parenthesis")]
        CloseParen,

        Subtract,
        Plus,
        Multiply,
        Divide,
        Comma,
        Or,
        And,
        Not,
        Dot,
        Function,
        Return,
        NewLine,
        Eof,
        For,
        To,
        Next,
        Step,
        In,
        Comment,
        Type,
        New,
        OpenBracket,
        CloseBracket,
        OpenBrace,
        CloseBrace,
        Property,
        Construct,
        EndFunction,
        IdentifierType,
    }
}
