namespace Quixotic.Lexography.Tokens
{
    public enum TokenType
    {
        StringLiteral,
        Identifier,
        NumberLiteral,
        Print,
        If,
        Then,
        Else,
        End,
        EqualTo,
        GreaterThan,
        LessThan,
        Assignment,
        LeftParen,
        RightParen,
        Subtract,
        Plus,
        Multiply,
        Divide,
        NewLine,
        Eof,
        Or,
        And,
        Not,
    }
}
