namespace Quixotic.Lexography.Tokens
{
    public enum TokenType
    {
        StringLiteral,
        Identifier,
        NumberLiteral,
        Print,
        If,
        Then,
        Else,
        End,
        EqualTo,
        NotEqualTo,
        GreaterThan,
        GreaterThanOrEqualTo,
        LessThan,
        LessThanOrEqualTo,
        Assignment,
        OpenParen,
        CloseParen,
        Subtract,
        Plus,
        Multiply,
        Divide,
        Comma,
        NewLine,
        Eof,
        Or,
        And,
        Not,
        Function,
    }
}
